basic_cart.settings:  
 type: mapping
 label: 'Basic cart settings'
 mapping:
  cart_page_title:
   type: string
   label: 'Cart Page Title'
  empty_cart:
   type: string
   label: 'Empty cart message'
  cart_block_title:
   type: string
   label: 'Cart block title'
  view_cart_button:
   type: string
   label: 'View cart button'
  cart_update_button:
   type: string
   label: 'Cart update Button Text'
  cart_updated_message:
   type: string
   label: 'Cart Updated message'
  quantity_status:
   type: integer
   label: 'Enable quantity'
  quantity_label:
   type: string
   label: 'Quantity label'
  price_status:
   type: integer
   label: 'Enable price'
  price_label:
   type: string
   label: 'Price label'
  total_price_status:
   type: integer
   label: 'Total price'
  total_price_label:
   type: string
   label: 'Total price label'
  currency_status:
   type: integer
   label: 'Currency Status' 
  currency:
   type: string
   label: 'Currency'
  price_format:
   type: string
   label: 'Price format'   
  vat_state:
   type: integer
   label: 'Enable VAT'
  vat_value:
   type: float
   label: 'VAT'
  add_to_cart_button:
   type: string
   label: 'Add to cart'
  add_to_cart_redirect:
   type: string
   label: 'Redirection after cart update'
  content_type:
   type: sequence
   label: 'Content Types'
   sequence:
    type: string
    label: 'Content type'
  order_status:
   type: integer
   label: 'Enable Basic Cart Order'
  langcode:
   type: string
   label: 'Language'
  added_to_cart_message:
   type: string
   label: 'Added to cart message'          
  use_cart_table:
   type: integer
   label: 'Enable cart in table'
        
    
    